### ISSUE TITLE
Handling Date attributes - fromPojo

### ISSUE THREAD

**Issue by zimoony** [essential-projects/data_model_contracts#8]
#### Describe your issue

When data is converted to JSON (e.g. here https://github.com/essential-projects/datastore_http/blob/608c30f48c23e289d2329a3ffb3dfa778e0d3682/src/datastore_controller.ts#L105) and passed to a datasource_adapter_proxy being the caller (which feeds the fromPojo function in data_model_contracts) the Date is naturally passed as a string. The fromPojo method does not handle that case at the moment - it need to be parsed.

#### How can others reproduce the issue?

Calling the getCollection method of the DatastoreService using the datasource_adapter_proxy retrieving entities with a Date attribute will result in the wrong behavior.

#### Possible solution

In fromPojo: When the property is of type Date (checked via schema), being actually a string and not null then try to parse it into a new Date().

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
As mentioned in #9 this should be handled in the `datasource_adapter_proxy`, not in `data_model_contracts`

**Comment by heikomat** [comment]
Closed in favour of essential-projects/datasource_adapter_proxy/issues/3
